<?php
/** @var  $block \ADM\QuickDevBar\Block\Tab\Panel */
?>
<p>
<?=  __('List only events dispatched when Magento generate this page')?>
</p>
<?php if ($block->getEvents()):?>
<table class="qdb_table striped filterable">
<thead>
<tr>
    <th>Event</th>
    <th>Data</th>
    <th>Call Number</th>
</tr>
</thead>
<tbody>
    <?php foreach ($block->getEvents() as $event): ?>
      <tr>
        <td><?= $block->escapeHtml($event['event']); ?></td>
        <td><?php if (!empty($event['args'])): ?><ul><?php foreach ($event['args'] as $arg): ?><li><?= $block->escapeHtml($arg) ?></li><?php endforeach; ?></ul><?php endif; ?></td>
        <td><?= (int)$event['nbr']; ?></td>
      </tr>
    <?php endforeach ?>
</tbody>
</table>
<?php endif;?>
